"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
var local_1 = require("next/font/local");
require("./globals.css");
var geistSans = (0, local_1.default)({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
var geistMono = (0, local_1.default)({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout(_a) {
    var children = _a.children;
    return (<html lang="en">
      <body className={"".concat(geistSans.variable, " ").concat(geistMono.variable)}>
        {children}
      </body>
    </html>);
}
